### ISSUE TITLE
[8] Temporal Filtering Backend

### ISSUE THREAD

**Issue by MaxVanDeursen** [vandenheuvel/tribler#124]
As a Developer I want to be able to filter the data on temporal terms so that I can see the network over a certain period of time

**Comment by vandenheuvel** [comment]
After some careful code reading I must conclude that this is, with the current version of TrustChain, not possible. The database table contains only an `insert_time` field which defaults to the current time stamp. This means that we only know when blocks where inserted into the database rather than when they were created.

As transactions are ordered there is a sequence number at every block. We might be able to use this for the same purpose. I however propose that we hold off this decision until we've thought carefully about what we actually want to build.

**Comment by vandenheuvel** [comment]
It was decided that we won't pursue temporal filtering any further right now as this feature is no longer realistic.
